# https://taskfile.dev

version: '3'

vars:
  ImageName: transfer
  ImageOwner: fsrv
  Version:
    sh: if [ -n "{{.CI_COMMIT_TAG}}" ]; then echo {{.CI_COMMIT_TAG}}; else date +%s; fi

tasks:
  build:
    cmds:
      - podman build --no-cache -t "{{.ImageName}}" .
  tag:
    cmds:
      - task: build
      - podman tag "{{.ImageName}}" "{{.ImageOwner}}/{{.ImageName}}:{{.Version}}"
      - podman tag "{{.ImageName}}" "{{.ImageOwner}}/{{.ImageName}}:latest"
  publish:
    cmds:
      - task: tag
      - podman push "{{.ImageOwner}}/{{.ImageName}}:{{.Version}}"
      - podman push "{{.ImageOwner}}/{{.ImageName}}:latest"
  default:
    cmds:
      - task: publish
